name: shared_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0-406.0.dev <3.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_resolvers: ^2.2.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
